### ISSUE TITLE
Animation Lab: "Add Animation Slide" will create new slide even with existing animation

### ISSUE THREAD

**Issue by Kenneth-LJS** [PowerPointLabs/PowerPointLabs#1146]
After adding a normal animation slide

![image](https://cloud.githubusercontent.com/assets/21071217/23009150/4732c346-f44f-11e6-9eac-6cf8df626782.png)
to
![image](https://cloud.githubusercontent.com/assets/21071217/23009158/52793a6e-f44f-11e6-809e-97418f9a0e64.png)

I can add another animation slide on the first slide, and it won't differentiate that the second slide is already an animation slide, but instead create another animation slide.

![image](https://cloud.githubusercontent.com/assets/21071217/23009167/61fe006e-f44f-11e6-8ce6-88d9b2cee695.png)

**Comment by damithc** [comment]
Users are supposed to delete animation slide first :-)

**Comment by Kenneth-LJS** [comment]
I find that while using there's usually a need to keep tweaking the animations and recreating the animation slide. Personally I haven't yet found a use case for creating an animation slide over the animation slide :P

**Comment by damithc** [comment]
> I find that while using there's usually a need to keep tweaking the animations and recreating the animation slide.

Yes you are right, it's better if the user doesn't have to delete the slide. In fact we used to have that feature until we decided it's too much work to maintain it anymore (it caused some tricky bugs). There are some other similar features that requires the user to delete the generated slide first before regenerating e.g. spotlight, so we decided it's also consistent and less work if we trained the user to delete the generated slides in all those features rather than try to implement an auto-reapply in all those features. Now that animation lab is deprecated, there is even more reason not to re-implement that feature. :-p
