### ISSUE TITLE
Sync Lab: Improve Sync Line

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1208]
- [x] Change "Line Style" to "Compound Type"
- [x] Add "Dash Type"
- [x] Add "Transparency"
- [ ] Add "Cap Type"
- [ ] Add "Join Type"

Anyone have any suggestions for better names? I feel that some of them like "Compound Type", "Cap Type" and "Join Type" are not very intuitive. But the names here are the same as what PowerPoint uses.

**Comment by IanTeo** [comment]
I am currently unable to find a way to edit the "Cap Type" and "Join Type"

**Comment by YuPeiHenry** [comment]
According to some sources, line cap and join types are not exposed. Some possible but difficult ways of manipulating them involves sending keystrokes, or using predefined shapes and the format painter. Closing issue because the effort far outweighs the benefit.

Sources:
https://stackoverflow.com/questions/13132047/ms-word-format-data-series-line-cap-type
https://stackoverflow.com/questions/5293014/join-types-in-powerpoint
