### ISSUE TITLE
Support naming copied attributes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1224]
When copying some attributes from an object, allow the user to specify a name for it (add a text box to the 'copy' dialog?). If the user does not specify a name, we can create a name based on the name of the object and the attributes copied.

**Comment by Kenneth-LJS** [comment]
> If the user does not specify a name, we can create a name based on the name of the object and the attributes copied.

This might not be a good idea because
- Displaying all the formats in use will clutter the GUI, and most of the text will either be (a) hidden with "...", or (b) make the line height inconsistent because more space is needed for the text.
- If the user updates the formats, the text will have to be updated. We will need to detect between user-specified names and auto-generated names so we don't accidentally replace user-specified names.

**Comment by damithc** [comment]
Perhaps you can show details of the style as a tool tip? Anyway, it's not that urgent. Can be left as future work.
