### ISSUE TITLE
Code Quality: Resolve SonarQube issue classified with "Blocker" severity

### ISSUE THREAD

**Issue by Skaty** [PowerPointLabs/PowerPointLabs#1346]
As of 3rd December, there are currently 3 issues (1 bug and 2 code smells) with a severity of "Blocker" in the SonarQube code analysis.

Given the following issues, the readability rating of the project is currently at "E" (as there is 1 "Bug"-type issue with "Blocker" severity).

These are the issues that needs to be addressed (click on any of them be redirected to the SonarQube page):

Bug
- [AutoUpdate/Downloader.cs - Line 11](https://sonarcloud.io/project/issues?id=powerpointlabs%3Amaster&issues=AVwti0vexDuieLkr2Tvq&open=AVwti0vexDuieLkr2Tvq)

Code Smells
- [PositionsLab/PositionsLabMain.cs - Line 1531](https://sonarcloud.io/project/issues?id=powerpointlabs%3Amaster&issues=AVwti050xDuieLkr2TzG&open=AVwti050xDuieLkr2TzG)
- [PositionsLab/PositionsLabMain.cs - Line 1708](https://sonarcloud.io/project/issues?id=powerpointlabs%3Amaster&issues=AVwti051xDuieLkr2TzP&open=AVwti051xDuieLkr2TzP)
- [PowerPointLabsPositionsLab/PositionsPaneWPF.xaml.cs - Line 1025](https://sonarcloud.io/project/issues?id=powerpointlabs%3Amaster&issues=AV1ZqeDeqjpHh2iq4c6Q&open=AV1ZqeDeqjpHh2iq4c6Q)

These issues should be fixed first, before any other issues that have been reported by SonarQube.

**Comment by leeyh20** [comment]
I can do this!

**Comment by leeyh20** [comment]
@Skaty To clarify, does the project need a common interface for disposing objects like `IDisposable`?

**Comment by leeyh20** [comment]
@Skaty Line 1025 at PositionsPaneWPF.xaml.cs cannot be fixed because it is `public void ExecutePositionsAction(Action<ShapeRange> positionsAction, bool isPreview, bool isConvertPPShape = true)` whereas Line 1227 is `public void ExecutePositionsAction(Action<List<PPShape>> positionsAction, bool isPreview)` thus the code signature is actually different but SonarQube thinks that they are the same.
