### ISSUE TITLE
Highlight Text does not provide a message that nothing has changed

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1474]
When a non-text fragment is selected or nothing is selected, using Highlight Text (Highlight Lab) does nothing, but does not inform the user that nothing has changed.

It may be better to grey out the button in that case instead.

**Comment by junkiattan** [comment]
Hey @initialshl,
some clarifications:
1. do you want me to provide an error message or grey out the button?
2. also if the length of selected text is zero, then it shouldn't be considered an error right?

**Comment by initialshl** [comment]
My opinion is that it should be greyed out in both cases, otherwise the popup error may annoy the user. 

Maybe you could discuss with the team for any better approach

**Comment by damithc** [comment]
Looks like in some cases we grey out features that are not applicable to the current selection. In other cases we give an error message. 
The error message approach can be annoying but this is not meant to be a frequent happening. The advantage is that we can give an explanatory message why the feature is not applicable.
Greying out saves the user additional clicks. It is also how normal PowerPoint ribbons work. Perhaps we can use the tooltip to explain when the feature can be used (in lieu of an error message). One slight disadvantage is that sometimes users think they have to pay to get the greyed out features. :-p

How about we use greying out as the default mechanism and use error messages when greying out cannot be used?

**Comment by initialshl** [comment]
Hi, no worries.
Greying out (and most other Ribbon UI functions) is handled using ActionFramework in our case. For example, refer to:
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ActionFramework/AnimationLab/AnimateInSlide/AnimateInSlideEnabledHandler.cs
You will need to find out about the current selection and return false to grey out.

**Comment by junkiattan** [comment]
@initialshl 

Is there any way to get the event where the Highlight Menu button is clicked instead? This is because I realized that the code in [HighlightTextFragments](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/HighlightLab/HighlightTextFragments.cs) or [HighlightTextActionHandler](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ActionFramework/HighlightLab/HighlightText/HighlightTextActionHandler.cs) only detects the type of selection after the actual "HighlightText" button has been pressed, not before. 

If there is an event for the menu button click, then maybe I can refreshRibbonControl everytime the menu button is clicked and grey out the button depending on the selection type checked in [HighlightTextEnabledHandler](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ActionFramework/HighlightLab/HighlightText/HighlightTextEnabledHandler.cs).

**Comment by initialshl** [comment]
As an Office API event, i have not seen it before.

I dont know whether this will work, but you can try adding onAction or getPressed to HighlightLab menu in ribbon.xml and adding its respective ActionFramework classes and see whether it registers: https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/Ribbon1.xml#L158

You can refer how to add onAction here: https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ActionFramework/AnimationLab/AnimateInSlide/AnimateInSlideActionHandler.cs
For getPressed, its working but currently unused anywhere else, just replace Action to Pressed and onAction to getPressed

**Comment by junkiattan** [comment]
@initialshl 

I cant seem to add either onAction or getPressed. The editor keeps telling me that the attribute is not declared.
