### ISSUE TITLE
Shapes Lab pane does not have an 'Add' button

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1498]
Adding shapes to Shapes Lab can only be done from the context menu, the pane should also have an 'Add Shape' button (similarly to Sync Lab).

**Comment by leeyh20** [comment]
I'll start on this!

**Comment by leeyh20** [comment]
@initialshl  Hi I would like to check, since `var selection = this.GetCurrentSelection();` is obsolete as we need to go through the Action Framework, how do I call the execute action of AddShapeActionHandler in the click event function (in CustomShapePane) of the "Add Shape" button?

I think I'll then need to display an error like sync lab if the selection is invalid? AddShapeActionHandler seems to assume that the selection will always be valid.

**Comment by initialshl** [comment]
Addshapeactionhandler is called from contextmenu button when right-clicking certain shapes, so the selection is always valid. Regarding the pane button, it does not need to be handled through action framework, but rather in its own function. We only use actionframework for ribbon and contextmenu.

It would be good to just extract out addshapeactionhandler operations into one method to be used by both.
