### ISSUE TITLE
Paste Lab: support 'smart paste' of photos

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1556]
When pasting a photo from internet, it often ends up being larger than the slide, needing manual adjustments. Furthermore, usually the resolution is higher than necessary, increasing the size of the ppt file. It would be nice if we can provide a 'smart paste' that can overcome these issues. Another thing we can do is to automatically insert a reference to the photo source.

**Comment by damithc** [comment]
yeah, those features were added recently and I forgot they existed. :-p
I guess auto-compressing and auto-citing is not easy to do. In that case we can close this issue. See if you can do an auto-compress if the user does a 'paste to fit slide'.

**Comment by junkiattan** [comment]
@damithc ,

does auto compress mean reducing a high resolution picture fit inside the dimensions of the slide while maintaining aspect ratio? also what is a expected action of "paste to fill"?

currently, what happens is that for pictures, regardless high or low size, they are made to match aspect ratio of each slide and then any excess is cropped away. This leads to the transition between 1 and 2, where 1 is "pasting in original position" and 2 is "paste to fill slide"

But I was wondering whether a transition from 1 to 3 would be better, since the aspect ratio is maintained but the picture is not cropped instead. When dealing with titles or words, cropping them in the case of 2 sort of looks ugly. Is 1->2 the intended action of "paste to fill"?

1 <img width="960" alt="pre-compress1" src="https://user-images.githubusercontent.com/16800272/35280771-2a4301f2-008c-11e8-8a07-e5f914a8eb9b.png">

2 <img width="960" alt="post-compress2" src="https://user-images.githubusercontent.com/16800272/35280798-3f6e9fd2-008c-11e8-94f7-706f8455c57a.png">

3 <img width="960" alt="post-compress1" src="https://user-images.githubusercontent.com/16800272/35280787-39533f9a-008c-11e8-986a-843280464b82.png">

**Comment by damithc** [comment]
By _compress_ I meant reduce the size of the file. A high res photo is usually about 3-5Mb but a normal ppt presentation doesn't need such high resolution.  PowerPoint already has a 'compress pictures' function (you can see that function in the ribbon of the 3rd screenshot). I'm wondering if we can apply that function automatically when we use the 'paste to fill slide' function, if the picture is bigger than the slide.

**Comment by junkiattan** [comment]
@initialshl 

Just to check, is there a conversion from PPShape to an Image or Bitmap and vice versa? Image/Bitmap has properties to set resolution and reduce if necessary and I want to ask if I can get the picture or image represented by the PPShape, change its resolution and convert it back to PPShape?

**Comment by initialshl** [comment]
Think there is, check the classes in util namespace
