### ISSUE TITLE
Enable hidden voices on Windows 10

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1574]
See if we can do this automatically:
https://www.trishtech.com/2016/12/enable-hidden-text-to-speech-voices-in-windows-10/

**Comment by Skaty** [comment]
Proposed solutions:
- Option during installation. Easy to integrate, since plugin installation would be run under elevated privileges. However, an option needs to be included to allow the user to enable the feature post-install.
- In the plug-in itself (option in Ribbon). Major issue: how do we request for the elevated privileges that are necessary to modify the registry?

**Comment by damithc** [comment]
It's fine if the feature works for future installs only. If somebody asks, we can always point the person to the above link or ask the person to reinstall PPL.

**Comment by damithc** [comment]
@alexfjw @junkiattan @leeyh20 
Can you guys actually get this trick to work in your current PPL installation? I enabled the voices as explained in the link but the new voices don't appear in the Narrations Lab settings. I'm using PPT 2013

**Comment by junkiattan** [comment]
@damithc

I have read the instructions! I will experiment with this and get back to you by tonight

**Comment by damithc** [comment]
Some info from Prof Henry (who managed to get it working):
>I also encountered this problem when I use my notebook (but not my office PC).  What I did was to do a search on the registry to find in which other places the voices are registered; I did a search for zira.  For my case, there was another entry under wow6432node (I can't remember the exact path though).  So I copied the registry entries over there.

**Comment by alexfjw** [comment]
Doesn't work for me either. From Prof Henry's workabout & the comment at the website, 
 
>I know this worked prior to 1703, but it doesn’t appear to work after the update? Any idea if this should work post 1703 or how to enable the same functionality?

could be that the directory for the registry entries changed after a major windows update.

**Comment by junkiattan** [comment]
I am experiencing the same issue.

Actually I think a possible solution would be to modify the registry values to include Eva and Mark voices in manually instead of running from the zip files.

I have checked the NarrationsLab files and they seem to be getting the voices from the system. Perhaps the Eva and Mark voices are somehow not included as part of the system?

Anyway I did some digging around and found out how to include them [manually](https://superuser.com/questions/1141840/how-to-enable-microsoft-eva-cortanas-voice-on-windows-10). The process is quite tedious and might cause some problems if not followed closely. I believe that after manually including both and rebooting com, all four voices should show up in NarrationsLab.

**Comment by damithc** [comment]
> could be that the directory for the registry entries changed after a major windows update.
> It's kinda strange. I did get Mark through the site above but not Eva in Microsoft's speech settings window. But none of them appear in PPTLabs

Most likely the scripts in the zip file needs to be updated to write the entries to a different location.

> Anyway I did some digging around and found out how to include them manually. The process is quite tedious and might cause some problems if not followed closely. I believe that after manually including both and rebooting com, all four voices should show up in NarrationsLab.

@junkiattan Did you try it yourself?

**Comment by leeyh20** [comment]
The scripts work for me because my laptop's Windows 10 is not updated, and they appear in PowerpointLabs too

**Comment by yuhongherald** [comment]
Closing issue as we are planning to retire NarrationsLab in favor of eLearningLab.
