### ISSUE TITLE
Do a 'crop to slide' when doing a 'paste to fill slide'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1584]
When doing a 'paste to fill slide' we can also do an automatic crop to fit the slide. Even better if PowerPoint goes to crop mode immediately so that the user can move the picture within the crop area to select exactly what part of the picture should remain in the view area.

**Comment by junkiattan** [comment]
@damithc 

I might be misunderstanding this issue, but I believe that crop-to-fit has already been included within the paste-to-fill function.

original image
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/16800272/35627954-715a99de-06d5-11e8-9b9a-af6104b3aeed.PNG">

image after paste-to-fill
<img width="960" alt="fillslide2" src="https://user-images.githubusercontent.com/16800272/35627945-6a33afe2-06d5-11e8-80a8-a629b9333d8c.png">

As can be seen, when paste to fill is used, the picture is expanded and any excess thereafter is cropped in order to allow it to fit the slide.

Is this what you meant for this issue?

**Comment by damithc** [comment]
> As can be seen, when paste to fill is used, the picture is expanded and any excess thereafter is cropped in order to allow it to fit the slide.

Yup, that's what I meant. It's fine then. We have so many features, I keep forgetting what we have :-p
