### ISSUE TITLE
SyncLab: The Fill Color of textboxes are inconsistent when using SyncLab

### ISSUE THREAD

**Issue by leeyh20** [PowerPointLabs/PowerPointLabs#1595]
Occurs in PPT 2010
// Edit: occurs in PPT 2016. (probably 2013 as well)

Notice that for this textbox, the fill color is black when trying to sync with SyncLab.
![image](https://user-images.githubusercontent.com/7023320/35927450-b2fd3fbe-0c65-11e8-9d6f-7a4ab3f534b7.png)

When I create a new textbox, the fill color mysteriously becomes the other blue color.
![image](https://user-images.githubusercontent.com/7023320/35927850-af84acd6-0c66-11e8-8fcb-ee51d996f0ad.png)

@alexfjw What do you think?

**Comment by alexfjw** [comment]
Could be a bug in how the fill format was implemented. Warrants some investigation

**Comment by alexfjw** [comment]
Turns out this is due to strange behavior that textboxes exhibit.

Fresh textboxes have a FillFormat type of msoFillMixed. (Fresh = just created and with no changes to style, etc) 
This type is only returned when there are two or more shapes in a shaperange, because they may have different fill properties.
At the same time, the fill of textboxes is transparent so it doesn't pose a problem.

Textboxes get a proper fill type after you fill them with a real color. (Proper = can be changed with code)

**Comment by alexfjw** [comment]
Adding on, it also turns out that the type of the textbox suddenly changes to msoFillSolid after the sync dialog is created. I couldn't find out exactly where this happens in the code even after tracing with a debugger, using the immediate window. Seems to be after creating the dialog item for the fill format.

The immediate window fails half the time and I think there's not much value going deeper for now.  We can attempt a quick fix that treats msoFillMixed as msoFillSolid since only fresh textboxes are affected.
