### ISSUE TITLE
Replace with clipboard: preserve shape settings

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1623]
When a picture is replaced with another using 'Replace with clipboard' feature, the new pictures seems to lose some of the properties of the previous one, such as the shadow effects. It would be good to preserve as many effects as possible.

**Comment by alexfjw** [comment]
Should be able to achieve this by using SyncLab behind the scenes, baring features not yet present in SyncLab. (shadows & other style effects) 
I'll look into this.

**Comment by alexfjw** [comment]
Would it make sense to preserve the clipboard item's height & width, rather than adopting it? 

It's probably more convenient for the clipboard item have it's height and width automatically changed to follow the object it is replacing, but the user might not want this all the time. (especially if the user's replacing a square with a rectangle, or circle with oval etc)

I'll go with preserving for now, unless there's other opinions on this.

**Comment by alexfjw** [comment]
We might be able to check if the clipboard item is a circle or square (since these are the only tricky shapes), and preserve height and width only in these cases. I think this might be slightly confusing for users though.
