### ISSUE TITLE
Port ColorsLab over to WPF

### ISSUE THREAD

**Issue by blewjy** [PowerPointLabs/PowerPointLabs#1778]
Currently, ColorsLab and ShapesLab are the only labs that are still using Windows Forms for the UI while the rest of the Labs with panes are using WPF. This issue is for porting over ColorsLab code into WPF. Mentioned in #478.

There is a change in behaviour of ColorsLab that I would like to propose, and it has been discussed offline with a couple of us but I would like to put it here for all to comment:

**Current behaviour:**
Currently, to apply a colour to a shape (be it font, fill or outline), user has to click and drag from one of the three buttons at the top of the pane to their desired colour to apply. I thought that this is not very intuitive, and if it weren't for the docs, it would take awhile for me to figure out how this works. 
![colors-lab-8](https://user-images.githubusercontent.com/39292809/52634179-7f604880-2f01-11e9-817d-242359d491f2.gif)

**Proposed:**
I think to make it easier and more straightforward, the user will simply select their desired colour, then click on one of the buttons to apply the colour to the shape. This should be more intuitive than the eyedropper function. We can then add a fourth button in the top row for users to select colours with the eyedropper as well. (Eyedropper not in the screenshot below)
![colors-lab-new](https://user-images.githubusercontent.com/39292809/52634889-5b056b80-2f03-11e9-83cf-0be28a669e9a.gif)

If there are any concerns, do mention here! Thanks

**Comment by damithc** [comment]
Note that this lab is mainly for picking colors from outside PowerPoint (e.g., from a web page). Picking colors from the color selection in the Lab itself is just a minor feature.
In that light, live preview and the magnifying glass is an important aspect of this lab (and it's the reason why this lab exists). Otherwise, we can use the built-in color picker of PowerPoint. While it's usage is unintuitive, once you've learnt it, it's more convenient than the standard way.  So, I would like to retain the current behavior but I don't mind adding the proposed behavior on top.

**Comment by damithc** [comment]
Actually, there is an alternative we can consider, which might alleviate the unintuitiveness of the feature UX.
We can lock into 'magnifying glass + live preview' mode upon clicking on the button (instead of requiring to click and drag). We can go back to normal mode upon clicking the button again, or picking a color, or pressing `ESC` key.

**Comment by blewjy** [comment]
Ok! That's no problem.

> We can lock into 'magnifying glass + live preview' mode upon clicking on the button (instead of requiring to click and drag). We can go back to normal mode upon clicking the button again, or picking a color, or pressing `ESC` key.

I think this is a good idea! I'll see how feasible it is and add it to the PR asap

**Comment by damithc** [comment]
> I think this is a good idea! I'll see how feasible it is and add it to the PR asap

I think we have a similar 'lock into mode' behavior in some feature of the positions lab
![image](https://user-images.githubusercontent.com/1673303/52644215-62d00a80-2f19-11e9-96d4-f2f94557ff58.png)
