### ISSUE TITLE
UI problem when using the the dark theme

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1902]
A user sent me this screenshot. 

![image](https://user-images.githubusercontent.com/1673303/57598538-382c3700-7586-11e9-9451-9300e333c3ef.png)

Any idea how to reproduce, and solve this problem?

**Comment by yuhongherald** [comment]
Reproduced on PPT 2016.
1. Go to file>account and change Office Theme to Black. Then open Resize Lab as per usual.
2. The dark color will remain persistent, even after switching to a different colored theme (look at previous step to change theme).

A solution to this problem is to use text colors consistent to the theme.
