### ISSUE TITLE
Highlight Lab: Background highlight disappears after adding point highlight

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1947]
#### Environment
PPT2016 Win10 dev-release 5.1.0.1
#### Steps to replicate
1. Create a new slide, add a point
2. Select all in the text box with the point
3. Highlight background
4. Highlight point
The background highlight is observed to not appear at all during slide show.

This is not observed when highlight background is replaced with highlight text.

**Comment by ccyccyccy** [comment]
I believe that it is this line causing the issue.
![image](https://user-images.githubusercontent.com/32454748/74048024-5be4b680-4a0c-11ea-88c2-9b7c1425b2d7.png)
which is called here:
![image](https://user-images.githubusercontent.com/32454748/74048086-7d45a280-4a0c-11ea-8988-2b910e8bf54e.png)

Seems like it is an intended behavior to remove all background highlights. Not sure if it's a bug then? I will try to find out if there's a reason for doing so.

**Comment by damithc** [comment]
> Seems like it is an intended behavior to remove all background highlights.

Do _highlight background_ and _highlight point_ clash with each other? i.e., only one should be used at any time? If not, there is no reason to remove one when the other is used.

**Comment by ccyccyccy** [comment]
>     3. Highlight background
> 
>     4. Highlight point

Actually the bug also happens when step 3 and 4 are swapped, i.e. highlighting background would overwrite highlighted points.

> Do _highlight background_ and _highlight point_ clash with each other? i.e., only one should be used at any time? If not, there is no reason to remove one when the other is used.

They don't clash, but I think it's more of a QOL feature. Normal usage usually don't make use of both highlights together.

**Comment by ChesterSng** [comment]
I think this issue can be changed to fixing the interaction between `highlight background` and `highlight text` instead following the discussion on PR #1947

**Comment by ChesterSng** [comment]
@ccyccyccy 
With regards to this [comment](https://github.com/PowerPointLabs/PowerPointLabs/pull/2006#issuecomment-590279345),
> This is not observed when highlight background is replaced with highlight text.

The reason for this issue is that the behaviour differs from using `highlight text` to `highlight background`. 

Since the behaviour for this issue is no longer regarded as a "bug", we should consider whether to change the interaction between `highlight background` and `highlight text` to replace each other (instead of being able to use both at the same time).

**Comment by ccyccyccy** [comment]
Got it. So maybe we can change it such that all highlight effects replace each other?

**Comment by ccyccyccy** [comment]
I found out that the animations would cancel each even if they are not overlapping.

![image](https://user-images.githubusercontent.com/32454748/75321146-20bb0200-58ab-11ea-8e6d-7d57554a3754.png)

So given the above slide, it is impossible to use PowerPointLabs to highlight one textbox with `Highlight Points` and the other one with `Highlight Background` since they would remove the each other. 

So maybe this is an issue worth fixing?

**Comment by damithc** [comment]
> So maybe this is an issue worth fixing?

Depends on the cost. If it involves a lot of work, we can always say only once of the two types can be used in a page. If there is a simple fix, we can go ahead.
