### ISSUE TITLE
'Replace with clipboard' feature seem to lose image quality

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#2002]
Our right-click menu has a feature 'Replace with clipboard' that can be used to replaces an image on a slide with another image currently copied into the clipboard.
However, this feature seems to degrade the image quality of the pasted image i.e., compared to the quality you get when pasting directly

**Comment by iskandarzulkarnaien** [comment]
I've discovered that the source of the bug is `ShapeUtil#ApplyAllPossibleFormats` which is being called inside `ReplaceWithClipboard#Execute`. 

@blewjy I don't quite understand the need to call `ApplyAllPossibleFormats` here since from my own testing it seems like its not needed, could you advise on this?

**Comment by iskandarzulkarnaien** [comment]
Also it seems that `ReplaceWithClipboard` is doesn't work quite as intended on shapes with many different formats applied:

![image](https://user-images.githubusercontent.com/43085796/76416298-c4d99880-63d5-11ea-949c-c6da00495fab.png)

**Comment by blewjy** [comment]
@iskandarzulkarnaien I just tested this and I'm encountering the same issues. I was able to reproduce Target 1 and Target 2 that you showed as well.

Commenting out `ApplyAllPossibleFormats` indeed seemed to fix the image quality issue, so something in there must be messing with the image quality. However I believe one of the original intention of `ApplyAllPossibleFormats` was to maintain the original formatting of the target shape/image whilst changing the content.

Try this for example:

Target image on the left, copied image on the right
![capt1](https://user-images.githubusercontent.com/39292809/76422087-9c569c00-63df-11ea-8e09-384c6b93e8d7.png)

Result:
![capt2](https://user-images.githubusercontent.com/39292809/76422125-ae383f00-63df-11ea-9d63-f76e576a9f64.png)

Without `ApplyAllPossibleFormats`, the green border is lost. The point of `Replace with Clipboard` in the first place is to maintain the formatting of the original shape/image, as well the animations, otherwise user can just simple Ctrl+C Ctrl+V, so this is a feature that we should keep. 

So although it seems a little unintuitive at first, actually the results that you showed in your last comment is actually intended. The image in Target 1 has no formatting, thats why only the text was kept. And in target 2 we kept the formatting (blue fill and nothing else) and replace the text.

My suggestion would be to see if we can fix the image quality issue from within the `ApplyAllPossibleFormats` call without changing the intended behaviour.. But open for discussion of course

**Comment by blewjy** [comment]
Just a side note: after playing around with it a bit more in PPT 2019, I realised that there's a PPT function (not sure if it's a new feature...?) under "Picture Format" that is "Change Picture", which does exactly what I showed with the green border thing, and still maintaining the original image quality... 🤣

**Comment by iskandarzulkarnaien** [comment]
>
> The point of Replace with Clipboard in the first place is to maintain the formatting of the original shape/image

Aiight thanks for the explanation, that makes much more sense now. This means that this is likely more an issue with the Sync lab than the Paste lab (since replace with clipboard relies on sync lab to maintain object formatting).

**Comment by iskandarzulkarnaien** [comment]
I've done some testing with synclab on images without any formatting (same picture was used as both target and source), and found that the following operations degrade the quality:

- ContourColorFormat
- ContourWidthFormat
- DepthSizeFormat
- LightingAngleFormat
- MaterialEffectFormat
- ThreeDRotationEffectFormat

**Comment by blewjy** [comment]
Ok cool, maybe you could try adding these formatting options as the ignored formats (right now only height and width are ignored), and see if it helps with the picture quality. You could also explore ignoring these only if the copied item is an image/picture, but include these formats if the copied item is a shape.

**Comment by iskandarzulkarnaien** [comment]
Thanks Bryan! Should I add a test to PasteLabFT that checks whether images are degraded by replace with clipboard?

**Comment by blewjy** [comment]
> Thanks Bryan! Should I add a test to PasteLabFT that checks whether images are degraded by replace with clipboard?

If it's a quick and simple test, sure. Otherwise I think you should prioritize getting the image to appear correctly first.
