### ISSUE TITLE
Clarify 32/64 bit compatibility

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#606]
Are we compatible with both? Perhaps clarify it somewhere?

**Comment by damithc** [comment]
@Ohohcakester can you add a clarification at an appropriate place in the documentation?

**Comment by Ohohcakester** [comment]
Are we compatible with both?

(on a side note, my windows is 64bit and office is 32bit.)

**Comment by kai33** [comment]
Yes we are compatible with both as long as
1. pptlabs add-in is built with Any CPU option (so e.g. the add-in codes are JIT to 32bit when powerpoint is 32bit, and JIT to 64bit when ppt is 64bit)
2. referenced Dlls also built with Any CPU, usually not a problem for public 3rd party lib.
3. use IntPtr, instead of int, to represent pointer for native methods like WIN API (IntPtr is 32/64bit compatible).

**Comment by kai33** [comment]
so generally, it's compatible :100:
