### ISSUE TITLE
visual agenda does not follow the slide background color of the first agenda slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#681]
If I change the slide background color of the first agenda slide, I expect other agenda slides to follow the same.

**Comment by nevet** [comment]
So background is another common thing and will be synced with the template, i.e. changes on each slide should not be preserved right?

**Comment by damithc** [comment]
Yes, background color changes to other agenda slides should be overwritten
by the background color of the first agenda slide.

**Comment by nevet** [comment]
It's a bit hard to do it right since background is not a simple property but a combination of some properties that could only be set by functions. Here I have 2 proposed ways to do it:

1. Save the background as a picture, then for each agenda slides we used that picture as background. The advantage of this method is it's simplicity. It would be fine for pattern type background, but for gradient or solid fill type background, it's hard to alter the configuration in agenda since it's no longer an editable shape, but a static picture;

2. Copy the reference slide and paste with "keep format" option. This method keeps the background as an editable shape.

For code complexity wise, method 1 could be finished in less than 10 lines based on the current code, but for method 2, some of the slide generation/ syncing logic must be rewritten to reduce redundancy.

**Comment by nevet** [comment]
Also, should this be applied to text agenda as well?

**Comment by damithc** [comment]
May be we don't need to support it if it hard/complicated to do. Users can
modify the master slide if they want to change the background color.
