### ISSUE TITLE
shapes lab slows down PowerPoint

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#687]
I noticed that PowerPoint slows down quite a lot when shapes lab is open. Noticed on both my comps. PPT2010.

**Comment by nevet** [comment]
Oh is it a new bug? I didn't notice this issue before.

**Comment by damithc** [comment]
I've noticed it a few times before but I didn't realize it was related to
shapes lab.

**Comment by nevet** [comment]
Could you elaborate more on this kind of slow down? Like what features are
affected, how it behaves before Shapes Lab opens and how it behaves after
Shapes Lab opens?

I tried to do a presentation with Shapes Lab opened but didn't notice
significant slow-down.

Best Regards,
Huang Da (Mr.)
National University of Singapore, Computer Engineering, Year 4
+65 86552730

**Comment by damithc** [comment]
All normal ppt operations start to lag. e.g. when I type a letter, it takes
a few seconds to appear on the slide. It might depend on the number of
categories and shapes you have, or even the size of the ppt file. Try with
one of the lecture slides I sent earlier, with about 10 categories and 10
shapes in each category.

**Comment by nevet** [comment]
Could you pack your shapes folder and send it to me? So that we could be in
the same situation.

On Saturday, March 21, 2015, Damith C. Rajapakse <notifications@github.com>
wrote:

> All normal ppt operations start to lag. e.g. when I type a letter, it takes
> a few seconds to appear on the slide. It might depend on the number of
> categories and shapes you have, or even the size of the ppt file. Try with
> one of the lecture slides I sent earlier, with about 10 categories and 10
> shapes in each category.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerPointLabs/repo/issues/687#issuecomment-84222180>.
>


-- 
Best Regards,
Huang Da (Mr.)
National University of Singapore, Computer Engineering, Year 4
+65 86552730

**Comment by nevet** [comment]
I tried on lab's machine (win7 2010), and it really slows down the reaction A LOT, the lag is observable. I tested several scenarios and found the reason should be:

The laggy does not due to the background Shapes Lab's powerpoint, but the taskpane redrawing. The more items inside the pane, the slower the powerpoint will react to an action.

Actually there are some other cases task pane slows down things without any reasons. For example, when I assign a width to a taskpane, it may take around 1s to do so. I will try to find a work around to fix this issue, since ShapesChef and MS Storyboard handles it well.

**Comment by nevet** [comment]
Bug located. It's because I handled every drawing event in the panel by overriding WndProc(), however inside the drawing event I somehow triggered another drawing event (didn't do it explicitly, need to check if it's done by other callbacks), and thus it falls into an infinite drawing loop. Since I double buffered the panel and all controls, so the drawing won't be reflected while we use the feature, but it consumes the CPU heavily.

**Comment by Ohohcakester** [comment]
Fixed in bca7f69bddefe711ec13fcf12eeac177e0aeb9c2
