### ISSUE TITLE
Common shapes in the template slide should maintain the object order

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#693]
e.g. if I put a shape in the template lab and make it go behind the text, the picture should appear behind the text in other agenda slides as well.

**Comment by damithc** [comment]
This also applies to objects in the template slide of visual agenda.

**Comment by Ohohcakester** [comment]
Fixed in 9a3f886f1ddf7d1f6e88dd1c32e5f72e64bd0a31

**Comment by damithc** [comment]
Not seem to be fixed in dev release V2.5.2.1. In visual agenda, generated slide images comes to the front although shaped I've put in were in front before the sync.
Before sync:
![image](https://cloud.githubusercontent.com/assets/1673303/8396166/3153d218-1dcd-11e5-840d-18f4da6032df.png)
after sync:
![image](https://cloud.githubusercontent.com/assets/1673303/8396168/4add7f72-1dcd-11e5-873c-5bd70f6c5c19.png)

**Comment by Ohohcakester** [comment]
Yes, but I left it this way for visual agenda images because when the zoom in is done, the image will be brought to the front during the zoom-in anyway. Thus I didn't want to give the impression that you can put the visual agenda images behind other objects.

No objects should be obstructing the image during a zoom-n.

**Comment by damithc** [comment]
Yes, that makes sense. So this issue is fixed? In that case, close the issue.
