### ISSUE TITLE
The initial template slide font size and spacing doesn't match the other agenda slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#712]
This example is from generating agenda slides for the 'quick tutorial' file:
![image](https://cloud.githubusercontent.com/assets/1673303/7786613/e4f82346-020c-11e5-9819-c2447e25aaea.png)

**Comment by damithc** [comment]
The annotation in the screenshot supposed to say 'line spacing'. It got truncated.

**Comment by nevet** [comment]
It's because of auto-fit feature, which causes #719 as well. So how should handle the case when the content will overflow the placeholder? Should we let it overflow and let user to adjust the the template slide, or adjust the template slide's font size and line space?

**Comment by damithc** [comment]
We can
1. disable autofit and handle everything manually.
2. add extra blank lines to the template slide so that text size and line
spacing ends up similar to other agenda slides.
Any other ideas?

**Comment by nevet** [comment]
I don't really understand point 2. Why we need to add blank lines to the template slide so that text size and line spacing ends up similar?

**Comment by damithc** [comment]
If all the agenda slides have the same number of lines, autofit will give
all them the same font size and line spacing right? The problem we now have
is the template slide has only 3 lines while other agenda slides might have
a different number of lines. That's why I suggested adding more lines to
the template slide.

**Comment by nevet** [comment]
Ic ic. Now I get it. So which one should we go with? I personally like point 2 because manually adjust font size and line space on just 3 lines may increase the difficulty of using the feature. @Ohohcakester could we fix on point 2? or any other suggestions?

**Comment by Ohohcakester** [comment]
I personally prefer point 1 (disable autofit, maybe by making the textbox large enough). Because we don't really have to make any forced adjustments if we disable autofit. The size will match the original, so we don't have to handle anything at all.
Seems like having autofit around would cause more need for manual adjustment, which is prone to bugs.

**Comment by nevet** [comment]
This is true, point 1 is much easier for developers, but may not be the easy for users.

**Comment by damithc** [comment]
Without autofit, you'll have to calculate the font size yourself right? It
will depend on how may topics in the agenda.

**Comment by Ohohcakester** [comment]
If autofit is not used, the font size would be supplied by the user, and thus the text may potentially go out of the slide if the agenda is too long.

**Comment by Ohohcakester** [comment]
Oh, but I see the problem for the initial generation of the agenda bullet points (before the user edits the template sldie)

**Comment by nevet** [comment]
So I guess point 2 will be used for current release?

**Comment by Ohohcakester** [comment]
I still personally prefer point 1, but I don't know whether point 2 will work out better. Let's go with point 2 then.

**Comment by nevet** [comment]
Ok lets do a pro vs. con

point 1: disable auto-fit
pros: easier to implement; less likely to introduce bugs because of auto-fit (such as #719);
cons: the initial generation of text agenda may go out of bound; more difficult for user to do the adjustment.

point 2: append blank lines to placeholder in template slide so that font size and line spacing are similar to other agenda
pros: template slide's font and line spacing are the same as other agenda slides;
cons: have potential to introduce bugs related to auto-fit (such as #719)

**Comment by Ohohcakester** [comment]
I don't think this issue (#712) itself is much of an issue, so either way works for me, but #719 seems to be something that is quite difficult to solve with autofit. For no autofit, we can programmatically choose the initial font size based on the amount of text, as @damithc suggested, so that the text will fit the screen. (we can do a rough estimate by selecting a suitable font-size/number of lines ratio)

**Comment by nevet** [comment]
The current commit 062b5b1 resolves #719 with auto-fit is enabled, so either way could resolve #712 and #719. However, estimating font size may not be as easy as it sounds. I do not have enough time to do experiments on coming up a good way to do the estimation, but you could do it since we might need this feature in the future :)

**Comment by Ohohcakester** [comment]
oh, okay then. let's go with option 2 since you've already resolved #719.
