### ISSUE TITLE
Give a way to copy-paste a template slide from another presentation.

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#718]
This is for text agenda.
Let's say I deleted the generated template slide and copy pasted a different template file from another presentation. When I try to sync, it shows this messages (correct behavior), and generates another new template slide. 
![image](https://cloud.githubusercontent.com/assets/1673303/7787428/0dc0bffa-023e-11e5-9415-9b8cf5addcb8.png)
The better way is to recognize the copy pasted template slide.

**Comment by nevet** [comment]
It's because copy-paste will rename the slide's name to default name, e.g. template slide's name is "PPTLabsAgendaReference", but after paste it becomes "SlideXX". It could be handled by hooking up after-paste event. The only problem is, the default copy-paste will set the slide's design to default as well. Should we retain the design as well for Agenda Lab? And should we override the default behavior? The current solution retain the design only for Agenda Lab's reference slide.

**Comment by damithc** [comment]
I don't like using hooks to intercept normal PowerPoint actions. Instead of
(or in addition to) using the slide name to identify the template slide,
you can use something in the slide to identify it. For example, you can
name the text box with a special name. In that case you can still identify
the template slide even if the slide got renamed. As for the design, it is
up to the user to keep the original design (that is a normal powerpoint
option).

**Comment by nevet** [comment]
My concern is, if we use a shape in the slide as an indicator, it's more vulnerable to user's "mistakes", e.g. user could delete the indicator, rename the indicator, and even put the indicator to another slide. It's harder to modify slide's name using only PPT's GUI, so I think using slide's name as indicator would be more secure.

As for the design, I didn't know it's already a powerpoint option :P I will revert the changes on this point :)

**Comment by Ohohcakester** [comment]
There is another issue with using the name. Some of the other PowerPointLabs effects (e.g. ZoomToArea) also change the name of the slide, which makes Agenda Lab unable to identify the slide.
The user being unable to view or change the name makes this problem more serious as the user will be unable to diagnose the error.

Regarding using the shape, there are two ways we can do it:
1) Make the shape a hidden shape - hidden shapes are difficult to detect and delete.
2) Make the indicator visible to the user, but make it clear that the indicator is being used to mark the template slide. This way, the user knows not to delete the indicator, and also has the option of moving the indicator to other "template slides" to switch the template slide.

I personally prefer option 2 as it gives the user more control and allows the user to diagnose errors more easily.
If there are multiple indicators, the first slide with an indicator is used (which is what I believe is currently being done if there somehow are multiple template slides with the same name)

**Comment by nevet** [comment]
Features should preserve the originality as much as it can. If change name is not intended in ZoomToArea, that's actually a bug, not a feature :P But anyway, option 2 looks better since it's more transparent to users about how we identify the template slide. I do not have enough time now, @Ohohcakester can you do it?

**Comment by damithc** [comment]
Yes, we can have a visible 'This is a template slide ...' object. In fact,
that can contain some instructions on how to use the template.

**Comment by Ohohcakester** [comment]
Just realised I forgot to reply. Yeah, I'll take over this issue.
