### ISSUE TITLE
Incorrect hyperlink in text agenda slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#719]
To reproduce, generate text agenda for quick tutorial. Hyper links for the last few agenda items are incorrect.

**Comment by nevet** [comment]
This is because of the auto-fit feature when the total height of the bullets is higher than the place holder. When this happens, bullets will change their font size, and thus the bounding rectangle, to fit in the placeholder. However, this auto-fit process is done after the custom-event handler, and the hyper link shapes are depending on the bounding box, thus the hyper links behaved weirdly.
