### ISSUE TITLE
Beam agenda blocks content

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#731]
example in Tutorial:
a paragraph is blocked by agenda beam (sidebar)
![tuto](https://cloud.githubusercontent.com/assets/3591355/8324038/84bb3e52-1a7e-11e5-864a-34adca918510.png)

What I previously expected:
this is prof Stephane Bressan's slide. its agenda looks slim & small
and I feel that this agenda shape can push the other shapes to move down a bit
so it doesnt block the content
![beamagenda](https://cloud.githubusercontent.com/assets/3591355/8324048/964be57c-1a7e-11e5-8a89-7f2c5f93e465.png)

**Comment by Ohohcakester** [comment]
Moving the shapes down to fit can make the shapes go off screen (then the problem becomes the same as if you placed a beam agenda at the bottom of the slide)

The beam is slim in the slide because there are only four agenda items, compared to much more in the example above.
An idea I have is to make the text fit the beam size instead of the beam size fit the text when synchronizing.
Then you would be able to create a slimmer beam using the following steps:
1) generate beam agenda
2) resize beam agenda to make it smaller
3) synchronize the beam agenda, and the text will auto-fit the beam.

What we will lose:
- Can no longer do manual placement of the text in the beam.
- User will have to manually resize the beam when he adds more sections, else the text may be too small. (It becomes a trade-off then, beam to fit the text, or text to fit the beam? currently it's the former)

**Comment by damithc** [comment]
It's a bit risky to move slide content to cater for agenda content. Let's assume the user should arrange content to fit the agenda type.
