### ISSUE TITLE
Text agenda: preserve slide transitions of agenda slides during sync

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#733]
We should not override slide transitions added by the user

**Comment by Ohohcakester** [comment]
fixed in e4e8a74b8553f96f181349d231be6ac8b641063d

New mechanism:
We apply the new transitions only to newly-generated slides. Slides which are already present will maintain their previous transition.

Note: one of the new transitions is applied to the user's slides, instead of a generated slide. A minor issue is that this change lingers even after agenda removal because it cannot be tracked.

**Comment by damithc** [comment]
Yes, that is a slight problem. Ideally, removing an agenda should get rid of all traces of it. If those slides already had transitions, do we override them?

**Comment by Ohohcakester** [comment]
They are overriden when the text agenda is generated.
That's why I don't really like changing things in the users' slides.
Unless we have a complex mechanism that stores data of their slides and serializes it into some metadata somewhere (e.g. in the notes page), we can't undo those changes.

**Comment by damithc** [comment]
You have a point. May be go back to not touching the user slides.

**Comment by Ohohcakester** [comment]
The difference in this case is not very big, though. Might be okay to allow a small exception in this case.
It will probably look weirder if we have the push animation for the transition into the agenda, but not for the transition out of the agenda.

**Comment by damithc** [comment]
Sure.
