### ISSUE TITLE
Should remove pptlabs customized close window

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#750]
1. it's a hack, not like a proper way of handling clean-up (we do a clean-up when ppt exits).
2. it's easy to break. e.g. open ppt app, open a slide, modify something, and then try to close the app ... then the customized close window failed to show up. (when open a slide by double-clicking its file, modify something, and then try to close ... then the customized close window will show up)
3. it's not i18n. it's strange for non-English users to see a msgbox with English instructions.

![close-window](https://cloud.githubusercontent.com/assets/3591355/8576108/7631f59c-25d2-11e5-9898-921f1b7617d7.jpg)

**Comment by damithc** [comment]
@nevet what was the reason for adding this? I remember you had some reason.

**Comment by nevet** [comment]
I remember it's related to taskpane-presentation association: for recorder pane, it's associated with the presentation, and the play list of this presentation is cached. When user closes the presentation, the cache needs to be cleared, and the association should be torn down. However, if you try to handle close presentation event, the event is triggered before the message box. This causes a problem: if user chooses NO, then the close presentation event executed wrongly.

I could not remember if there were other reasons for me to do this, but I suggest to remove it first, and run all tests to see if there are any regressions since it's much easier to test the whole app now.
