### ISSUE TITLE
Error during auto update to new version

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#794]
Here's the text of the error message

Name: PowerPointLabs - PowerPointLabs
From: http://www.comp.nus.edu.sg/~pptlabs/....

*************\* Exception Text **************
System.Runtime.InteropServices.COMException (0x8007001F): A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by damithc** [comment]
As a result, the addin got disabled. 
I re-enabled it. Seems to be fine now.

**Comment by kai33** [comment]
looks like a ClickOnce problem:
http://stackoverflow.com/questions/2138683/clickonce-upgrade-fails-system-deployment-internal-isolation-storetransactionop

may need to set up a troubleshoot page

**Comment by damithc** [comment]
Happened again, just like during the previous update. It never happened before that though.

**Comment by kai33** [comment]
Cannot re-produce in my device.

Would you mind to update to the recent VSTO runtime?
VSTO runtime download link here:
http://www.comp.nus.edu.sg/~pptlabs/vsto-redirect.html

According to this article:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/495098f8-6364-443a-b2e1-23e650af7e1e/exception-customization-could-not-be-loaded-because-the-application-domain-could-not-be-created-?forum=vsto

It's a bug from old ClickOnce that
> We have recently discovered an issue where add-ins deployed using the ClickOnce method will, under certain conditions, try and fail to install an update, and thereby disable the add-in.

**Comment by damithc** [comment]
I'll update now and will report if it happens again.

**Comment by damithc** [comment]
Didn't happen after updating VSTO runtime.

**Comment by damithc** [comment]
Should I update VSTO again?

**Comment by damithc** [comment]
Old issue. Closing.
